# Generated by Django 3.2.4 on 2021-06-28 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('rent', 'rent'), ('investment', 'investment')], max_length=50)),
                ('beneficiary_name', models.TextField()),
                ('rent_cost', models.IntegerField()),
                ('rent_ferquency', models.CharField(choices=[('monthly', 'rent'), ('yearly', 'investment')], max_length=50)),
                ('contract_holder_name', models.TextField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('first_rent_due_date', models.DateField()),
                ('notes', models.TextField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.unit')),
            ],
        ),
    ]
