# Generated by Django 3.2.4 on 2021-06-28 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.CharField(choices=[('residential', 'residential')], max_length=50)),
                ('number_of_floors', models.IntegerField()),
                ('units_per_floor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('phone', models.TextField()),
                ('floor', models.IntegerField()),
                ('number', models.IntegerField()),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.estate')),
            ],
        ),
    ]
