# Generated by Django 3.2.3 on 2022-02-14 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estate',
            old_name='type',
            new_name='estate_type',
        ),
    ]
