# Generated by Django 3.2.3 on 2021-06-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('total_offline_collected', models.IntegerField()),
                ('total_online_collected', models.IntegerField()),
                ('total_pending', models.IntegerField()),
            ],
        ),
    ]
