# Generated by Django 3.2.3 on 2022-03-22 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='renter',
            old_name='location',
            new_name='name',
        ),
    ]
