# Generated by Django 3.2.3 on 2021-06-28 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('paid', 'paid'), ('late', 'late'), ('due', 'due'), ('upcoming', 'upcoming'), ('canceled', 'canceled')], max_length=50)),
                ('date', models.DateField()),
                ('payment_method', models.CharField(choices=[('fawry', 'fawry')], max_length=50)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.unit')),
            ],
        ),
    ]
